"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os

# ==========================
# المسار الأساسي للمشروع
# ==========================
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================
# الإعدادات الأمنية
# ==========================
SECRET_KEY = 'django-insecure-1dfdy#n-1))%8@q)7!kg)kw#=91c8j@m#&6i9&f)dout2#a@@v'
DEBUG = True
ALLOWED_HOSTS = []

# ==========================
# التطبيقات المثبتة
# ==========================
INSTALLED_APPS = [
    # تطبيقات Django الافتراضية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # التطبيقات الخاصة بالمشروع
    'users',
    'marketplace',
    'payments',
]

# استبدال نموذج المستخدم الافتراضي
AUTH_USER_MODEL = 'users.CustomUser'

# ==========================
# Middleware
# ==========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',   # دعم تعدد اللغات
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==========================
# روابط المشروع
# ==========================
ROOT_URLCONF = 'school.urls'

# ==========================
# القوالب (Templates)
# ==========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # مجلد القوالب العام
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school.wsgi.application'

# ==========================
# قاعدة البيانات
# ==========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ==========================
# التحقق من كلمات المرور
# ==========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==========================
# اللغات والتوقيت
# ==========================
LANGUAGE_CODE = 'ar'            # واجهة عربية
TIME_ZONE = 'Asia/Riyadh'       # توقيت الرياض
USE_I18N = True
USE_TZ = True

# ==========================
# الملفات الثابتة (Static)
# ==========================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # تأكد من إنشاء مجلد static في الجذر
STATIC_ROOT = BASE_DIR / "staticfiles"    # لتجميع الملفات عند الإنتاج

# ==========================
# ملفات الوسائط (Media)
# ==========================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"           # تأكد من إنشاء مجلد media في الجذر

# ==========================
# الإعدادات الافتراضية للمفاتيح الأساسية
# ==========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
